### ISSUE TITLE
PIO constructor type mismatch

### ISSUE THREAD

**Issue by utdrmac** [fivesixzero/CircuitPython_HX711#5]
Per suggestions in #4, I'm trying to use the PIO version with my PicoW:

```
# HX711 Setup
gpio_data = digitalio.DigitalInOut(board.GP18)
gpio_clk = digitalio.DigitalInOut(board.GP19)

hx = HX711_PIO(gpio_data, gpio_clk, tare=False, offset=-155118, scalar=8949.0)
```

Error when running:
```
Traceback (most recent call last):
  File "<stdin>", line 50, in <module>
  File "hx711/hx711_pio.py", line 87, in __init__
  File "hx711/hx711_pio.py", line 102, in sm_init
TypeError: first_in_pin must be of type Pin, not DigitalInOut
```

The constructor for HX711_PIO [wants a DigitalInOut](https://github.com/fivesixzero/CircuitPython_HX711/blob/main/hx711/hx711_pio.py#L71) but [rp2pio.StateMachine](https://github.com/fivesixzero/CircuitPython_HX711/blob/main/hx711/hx711_pio.py#L97-L107) wants a `Pin` (https://docs.circuitpython.org/en/latest/shared-bindings/rp2pio/index.html)

**Comment by fivesixzero** [comment]
Oof, looks like I added type hints without double-checking and re-testing the PIO lib back in the day. 🤦 

I should be able to get this changed, tested, and committed to the repo within the next 24 hours or so.

**Comment by fivesixzero** [comment]
Although the constructor's type hints are incorrect (whoops), I did just run a test that worked fine as long as the board's `Pin` objects themselves are just passed through without using `DigitalInOut` at all, as in the PIO-mode example:

https://github.com/fivesixzero/CircuitPython_HX711/blob/4efc13f5e69f482d9b43936077e19e5fbeb7f285/examples/hx711_pio_simpletest.py#L8-L11

Give that a shot and let me know how it goes. I tested on a PicoW running the latest stable CircuitPython release (8.0.5) using `board.GP18` and `board.GP19`. Give that a shot and let me know if it works out.

Those type hints definitely need fixing though, so I'll be getting that addressed ASAP.

**Comment by utdrmac** [comment]
Hey @fivesixzero,
I finally had a chance to test this out:

```
# HX711 Setup
gpio_data = board.GP19
gpio_clk = board.GP18

# Initialize the HX711 ADC
# Don't tare on startup as the offset and scalar values are already calibrated
hx = HX711_GPIO(gpio_data, gpio_clk, tare=False, offset=-155118, scalar=8949.0)

...

Traceback (most recent call last):
  File "<stdin>", line 50, in <module>
  File "hx711/hx711_gpio.py", line 43, in __init__
AttributeError: 'Pin' object has no attribute 'switch_to_input'
```

**Comment by utdrmac** [comment]
Hey @fivesixzero I finally got a chance to test this and switching my code as follows results in all 0 for data:

```
**
** GPIO
from hx711.hx711_gpio import HX711_GPIO
# HX711 Setup
gpio_data = digitalio.DigitalInOut(board.GP19)
gpio_clk = digitalio.DigitalInOut(board.GP18)

# Initialize the HX711 ADC
# Don't tare on startup as the offset and scalar values are already calibrated
hx = HX711_GPIO(gpio_data, gpio_clk, tare=False, offset=-155118, scalar=8949.0)


**
** PIO
from hx711.hx711_pio import HX711_PIO
# HX711 Setup
gpio_data = board.GP19
gpio_clk = board.GP18

# Initialize the HX711 ADC
# Don't tare on startup as the offset and scalar values are already calibrated
hx = HX711_PIO(gpio_data, gpio_clk, tare=False, offset=-155118, scalar=8949.0)
```

Both are used as such:
```
    # Take 20 ADC readings, which are averaged
    reading = hx.read(20)
    reading_raw = hx.read_raw()
```
Both variables are then pushed to mqtt into influxdb. The GPIO version gives values whereas the PIO version gives 0s for both.
